import time
time.sleep(5)
print("I")
time.sleep(1)
print("LOV")
time.sleep(1)
print("Your")
time.sleep(1)
print("PC")
time.sleep(2)
print("Loading...")
time.sleep(5)
print(" ")
print(" ")
print("Done")
print("hbnejbhrv")
from subprocess import call
call(["python", "YourAcutie.TXT.py"])
time.sleep(1)
## REMENDER add another FailSafe if the Main FailSafe doesn't work.
